config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users

  mount Bpe::V1::Api, at: '/api'

  authenticate :user do
    mount GrapeSwaggerRails::Engine => '/swagger'
  end

  unauthenticated :user do
    devise_scope :user do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  root to: 'welcome#index'
  get '/*frontend', to: 'welcome#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image_uploader.rb
class ImageUploader < Shrine
 # plugin :determine_mime_type
 # plugin :remove_attachment
#  plugin :store_dimensions
#  plugin :validation_helpers
#  plugin :pretty_location
 # plugin :versions

  #Attacher.validate do
   # validate_max_size 5.megabytes, message: 'is too large (max is 5 MB)'
    #validate_mime_type_inclusion ['image/jpeg', 'image/png', 'image/gif']
  #end
end

app/models/photo.rb
class Photo < ApplicationRecord
  include ImageUploader[:image]
end

app/models/role.rb
# frozen_string_literal: true

class Role < ApplicationRecord
  has_many :roles_users
  has_many :users, through: :roles_users

  validates :name, presence: true, uniqueness: { case_sensitive: false }
end

app/models/roles_user.rb
# frozen_string_literal: true

class RolesUser < ApplicationRecord
  belongs_to :user
  belongs_to :role

  validates :user, presence: true
  validates :role, presence: true
end

app/models/state.rb
# frozen_string_literal: true

class State < ApplicationRecord
  has_one :next_state, class_name: 'State', foreign_key: 'from_state_id'
  belongs_to :from_state, class_name: 'State'
  has_many :vehicles, dependent: :destroy

  validates :from_state,
            presence: { allow_blank: true },
            uniqueness: { allow_blank: true }
  validates :name, presence: true
  validate :validate_from_state_id

  before_destroy :check_dependent_state

  json(:index,
       only: %i[id name],
       include: { from_state: { only: %i[id name] } })

  json(:detail,
       only: %i[id name],
       include: { from_state: { only: %i[id name] } })

  def self.initial
    where(from_state_id: nil).first
  end

  def self.list
    find_by_sql(rcte)
  end

  def self.rcte
    <<-SQL
        with recursive next_state AS (
          select * from states where states.from_state_id IS NULL
          union all
          select s.* from states as s join next_state AS ns on (s.from_state_id = ns.id)
        )
        select * from next_state
      SQL
  end

  private

  def validate_from_state_id
    return if from_state_id.blank?
    return if State.where(id: from_state_id).exists?
    errors.add(:from_state, 'Previous state not exists!')
  end

  def check_dependent_state
    return true if next_state.blank?
    errors.add(:next_state, 'Cannot delete, a dependent state exists!')
    throw(:abort) if errors.present?
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :rememberable, :validatable

  has_many :roles_users
  has_many :roles, through: :roles_users

  validates :first_name, presence: true
  validates :last_name, presence: true

  json(:index,
       only: %i[id email first_name last_name],
       methods: %i[is_admin])

  def role?(role_name)
    roles.where(name: role_name).exists?
  end

  def admin?
    role?('admin')
  end
  alias is_admin admin?
end

app/models/vehicle.rb
# frozen_string_literal: true

class Vehicle < ApplicationRecord
  belongs_to :state

  validates :name, presence: true
  validates :state, presence: true
  validate :valid_state_transition?

  before_validation :initial_state

  json(:index,
       only: %i[id name],
       methods: %i[has_next_state],
       include: { state: State.json(:index) })

  json(:detail,
       only: %i[id name],
       methods: %i[has_next_state],
       include: { state: State.json(:index) })

  def next_state?
    state.next_state.present?
  end
  alias has_next_state next_state?

  def next_state!
    if state.next_state.blank?
      errors.add(:state, 'No more state transition available')
      return false
    end

    self.state = state.next_state
    save!
  end

  private

  def valid_state_transition?
    return true unless state_id_changed?
    return true if state.from_state_id == state_id_was

    old_state = State.find(state_id_was)
    errors.add(:state, "Invalid transition from #{old_state.name} to #{state.name}")
  end

  def initial_state
    return if state.present?
    self.state = State.initial
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image)
    end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title>Vehicle state administaration</title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= yield %>

  </body>
</html>

app/views/photos/_form.html.erb
<%= form_for(photo, multipart: true) do |f| %>
<% if photo.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

  <ul>
    <% photo.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="field">
  <%= f.label :image_data %>
  <%= f.file_field :image %>
</div>

<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/photos/edit.html.erb
<h1>Editing Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Show', @photo %> |
<%= link_to 'Back', photos_path %>

app/views/photos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Photos</h1>

<table>
  <thead>
    <tr>
      <th>Image data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <td><%= photo.image_data %></td>
        <td><%= link_to 'Show', photo %></td>
        <td><%= link_to 'Edit', edit_photo_path(photo) %></td>
        <td><%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo', new_photo_path %>

app/views/photos/new.html.erb
<h1>New Photo</h1>

<%= render 'form', photo: @photo %>

<%= link_to 'Back', photos_path %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image data:</strong>
  <%= @photo.image.url %>
  <%= image_tag @photo.image.url %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>

app/views/welcome/index.html.erb
<% if current_user %>
<nav class="menu">
  <h1 class="name"><i class="fi-widget"></i><%= "#{current_user.first_name} #{current_user.last_name}" %></h1>
  <ul class="inline-list">
    <li><%= link_to 'Api explorer', grape_swagger_rails_path %></li>
    <li><%= link_to 'Log_out', destroy_user_session_path, class: 'logout' %></li>
  </ul>
</nav>
<% else %>
<%= link_to 'Log in', new_user_session_path %>
<% end %>

<div id="react-app"> </div>
<%= javascript_include_tag 'vendor.bundle' %>
<%= javascript_include_tag 'bundle' %>